### ISSUE TITLE
Angular SSR

### ISSUE THREAD

**Issue by ikbenignace** [Enngage/ngx-captcha#149]
Hi

The package does not work with Angular SSR.

**Comment by Enngage** [comment]
Hi, 

I don't quite see how ReCaptcha would work on server side. The validation is intended to by executed on the client side and you have to make sure to only use this library on the client side. Have a look at https://angular.io/api/common/isPlatformBrowser which might help.

**Comment by ikbenignace** [comment]
You do get a document undefined error because it just runs also in angular universal, so the module has to be changed and has to check on isPlatformBrowser, not me

**Comment by Enngage** [comment]
If you don't use the ngx-captcha component then you don't get this error, right? So, why not just use the `isPlatformBrowser` to conditionally render (or not render) the component? 

Or do you get the error if you just import the module? Imho I don't think thats the case. Or is there any reason why you couldn't wrap it in the `isPlatformBrowser`?

**Comment by ikbenignace** [comment]
Because it's you have to inport it in your whole module, so I get this problem on every page

**Comment by ikbenignace** [comment]
Also, the where it is on it, also needs to be server rendered

**Comment by ikbenignace** [comment]
It already start with this issue:

`ERROR ReferenceError: window is not defined
    at ReCaptcha2Component.registerCallbacks (C:\Users\mella\vrijwilligerswerk\dist\vrijwilligerswerk\server\main.js:4435:138340)
    at ReCaptcha2Component.captchaSpecificSetup (C:\Users\mella\vrijwilligerswerk\dist\vrijwilligerswerk\server\main.js:4435:137973)
    at ReCaptcha2Component.setupComponent (C:\Users\mella\vrijwilligerswerk\dist\vrijwilligerswerk\server\main.js:4435:132977)
    at ReCaptcha2Component.ngAfterViewChecked (C:\Users\mella\vrijwilligerswerk\dist\vrijwilligerswerk\server\main.js:4435:131590)
    at callHook (C:\Users\mella\vrijwilligerswerk\dist\vrijwilligerswerk\server\main.js:1297:2874)
    at callHooks (C:\Users\mella\vrijwilligerswerk\dist\vrijwilligerswerk\server\main.js:1297:2397)
    at executeInitAndCheckHooks (C:\Users\mella\vrijwilligerswerk\dist\vrijwilligerswerk\server\main.js:1297:1733)
    at refreshView (C:\Users\mella\vrijwilligerswerk\dist\vrijwilligerswerk\server\main.js:1844:5153)
    at refreshComponent (C:\Users\mella\vrijwilligerswerk\dist\vrijwilligerswerk\server\main.js:1844:23424)
    at refreshChildComponents (C:\Users\mella\vrijwilligerswerk\dist\vrijwilligerswerk\server\main.js:1844:999)`

**Comment by ikbenignace** [comment]
But i fixed it myself
https://github.com/ikbenignace/ngx-captcha

**Comment by Enngage** [comment]
Right, but if you don't render the component the `registerCallbacks` should never be called, so why can't you just not render the `ngx-captcha` if you are in SSR environment? 

If this error happens even if you don't use the `ngx-captcha` component and only import the module, then it would indeed have to fixed here. I don't really know if Angular compiler statically analyzes the code in SSR which then causes this error, but I would guess that is not the case.
