### ISSUE TITLE
is IE 11 supported for this reCaptcha V3?

### ISSUE THREAD

**Issue by koladilip** [Enngage/ngx-captcha#40]
I am getting the following error for reCaptcha V3 but it is working for V2.
Error: Uncaught (in promise): Error: Invalid site key or not loaded in api.js: MyGoogleCaptchaV3SiteKey
Error: Invalid site key or not loaded in api.js: MyGoogleCaptchaV3SiteKey
   at Anonymous function (https://www.gstatic.com/recaptcha/api2/v1547447582668/recaptcha__en.js:511:233)
   at Anonymous function (https://account-dev.aia.org/main.de0743aacc727a176234.js:1:1437121)
   at t.prototype.invoke (https://account-dev.aia.org/polyfills.2723677d4ab6e882c192.js:1:8287)
   at e.prototype.run (https://account-dev.aia.org/polyfills.2723677d4ab6e882c192.js:1:3535)
   at e.prototype.runOutsideAngular (https://account-dev.aia.org/main.de0743aacc727a176234.js:1:942652)
   at Anonymous function (https://account-dev.aia.org/main.de0743aacc727a176234.js:1:1437085)
   at Anonymous function (https://account-dev.aia.org/main.de0743aacc727a176234.js:1:1434600)
   at t.prototype.invoke (https://account-dev.aia.org/polyfills.2723677d4ab6e882c192.js:1:8287)
   at onInvoke (https://account-dev.a"

**Comment by Enngage** [comment]
I don't know about IE, but are you setting site key? :) Its right in the parameters of the method:¨

```
  this.reCaptchaV3Service.execute('what is your site key?', 'homepage', (token) => {
    console.log('This is your token: ', token);
  }, {
    useGlobalDomain: false // optional
  });
```

**Comment by koladilip** [comment]
Sorry, this is working now. I think I didn't properly clear the cache after the site is updated.
